---
# tasks file for aadl.websocketd
- name: Download Websocketd Binary
  get_url:
    url: "https://github.com/joewalnes/websocketd/releases/download/v{{ websocketd_version }}/websocketd-{{ websocketd_version }}-linux_amd64.zip"
    dest: /tmp/websocketd.zip
    checksum: "{{ websocketd_checksum }}"

- name: Extract Websocketd binary
  unarchive:
    src: /tmp/websocketd.zip
    dest: /tmp/
    remote_src: yes

- name: Install Websocketd Binary
  copy:
    src: /tmp/websocketd
    dest: "{{ websocketd_install_path }}/websocketd"
    mode: '0555'
    remote_src: yes

- name: Copy Systemd Service
  template:
    src: websocketd.service.j2
    dest: /lib/systemd/system/websocketd.service
    owner: root
    group: root
    mode: '0644'
  when: ansible_service_mgr == 'systemd'

- name: Enable Systemd Service
  systemd:
    name: websocketd
    enabled: yes
    masked: no
  when: ansible_service_mgr == 'systemd'
